### ISSUE TITLE
Unsupported structPropertyType 'InventoryToRespawnWith'

### ISSUE THREAD

**Issue by robison4th** [GreyHak/sat_sav_parse#1]
The save files and scripts are located in the same directory. Executing with python on Windows via PowerShell. 

> PS C:\Users\Robison4th\Downloads\sav_parse_v1.0_to_html> py sav_to_html.py survival.sav
> Traceback (most recent call last):
>   File "C:\Users\Elden\Downloads\sav_parse_v1.0_to_html\sav_to_html.py", line 125, in <module>
>     (saveFileInfo, headhex, grids, levels) = sav_parse.readFullSaveFile(savFilename)
>                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Robison4th\Downloads\sav_parse_v1.0_to_html\sav_parse.py", line 3463, in readFullSaveFile
>     (offset, level) = parseLevel(offset, data, True) # Potentially sets the global satisfactoryCalculatorInteractiveMapFlag
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Robison4th\Downloads\sav_parse_v1.0_to_html\sav_parse.py", line 2932, in parseLevel
>     offset = object.parse(offset, data, actorAndComponentObjectHeaders[idx])
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Robison4th\Downloads\sav_parse_v1.0_to_html\sav_parse.py", line 2597, in parse
> (offset, self.properties, self.propertyTypes) = parseProperties(offset, data)
>                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Robison4th\Downloads\sav_parse_v1.0_to_html\sav_parse.py", line 3298, in parseProperties
>     raise ParseError(f"Unsupported structPropertyType '{structPropertyType}'")
> sav_parse.ParseError: Unsupported structPropertyType 'InventoryToRespawnWith'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Robison4th\Downloads\sav_parse_v1.0_to_html\sav_to_html.py", line 595, in <module>
>     raise Exception(f"ERROR: While processing '{savFilename}': {error}")
> Exception: ERROR: While processing 'survival.sav': Unsupported structPropertyType 'InventoryToRespawnWith'

The save.html file was generated, but did not display anything besides the text of the error: Unsupported structPropertyType 'InventoryToRespawnWith'

This is just an assumption, but maybe this script is not currently configured to handle saves that are setup with Keep Inventory: Everything?

**Comment by GreyHak** [comment]
@robison4th Thank you for the report. So sorry I just saw it. I missed the email notice. I'll see what I can do to fix it tomorrow. I should be able to reproduce the issue with your information.

**Comment by GreyHak** [comment]
@robison4th Unfortunately I have been unable to reproduce the "InventoryToRespawnWith" property. In order to parse a new property I would need a sample save file that contains it as I would need to review the binary data to determine the format of the property. Could you please attach one? Thank you.

**Comment by robison4th** [comment]
survival.sav is the save I believe I was using when first attempting to test the script. modded.sav is my most recent save file that has been modded. (I don't know if your script supports mods, so survival.sav was created before I ever loaded mods). I hope this helps, thanks in advance for looking into this. 
[satisfactory-saves.zip](https://github.com/user-attachments/files/17485676/satisfactory-saves.zip)

**Comment by GreyHak** [comment]
@robison4th Thank you for sharing both files.  I didn't have an example Epic save which was causing may of the original issues (which you didn't see).  I still don't know why you have a InventoryToRespawnWith property.  Maybe a mod?  I've also added support for the mod properties in your other save.  Both these files are now supported by my parser.

**Comment by robison4th** [comment]
My 1.0 playthrough was on a fresh install of Satisfactory 1.0 once it was released. To my knowledge, that survival.sav save file should not have contained any mods. It was the last save I made prior to installing Satisfactory Mod Loader. 

I've tested the new release of the scripts and after downloading the OpenSource DejaVu Fonts from here: [https://dejavu-fonts.github.io/Download.html](https://dejavu-fonts.github.io/Download.html)

I was able to get these scripts to work. Thank you for all your work on this. 

Potential Consideration: I am on a relatively fresh and clean install of Windows 11. I do not believe this font comes standard with Windows. It was not located in: C:\Windows\Fonts until I downloaded and added it. 

If possible, maybe consider including the OpenSource font in the release? Or choosing one that is included by default on most/all OS as a fallback?

Just as additional information, here is the error I received prior to installing the required font:
`Traceback (most recent call last):
  File "C:\Users\Robison4th\Downloads\sav_parse_v1.4_full_release\sav_to_html.py", line 474, in generateHTML
    imageFont = ImageFont.truetype(FONT_FILENAME, MAP_FONT_SIZE)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robison4th\anaconda3\Lib\site-packages\PIL\ImageFont.py", line 879, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "C:\Users\Robison4th\anaconda3\Lib\site-packages\PIL\ImageFont.py", line 876, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robison4th\anaconda3\Lib\site-packages\PIL\ImageFont.py", line 284, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource`

**Comment by GreyHak** [comment]
@robison4th Interesting.  Thank you for letting me know.  I had tested font load failures, but I never got an OSError exception testing on Windows 11 Pro and Ubuntu.  I'll make some updates to better handle and report more useful information to the user.
