### ISSUE TITLE
structPropertyType 'FGPlayerPortalData' not supported

### ISSUE THREAD

**Issue by EricDechane** [GreyHak/sat_sav_parse#3]
It appears that there is a new feature in 1.0 that is not yet supported: Portals.

Terminal output of sav_cli.py:

> alec@Manjaro:~/sandbox:# python ~/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_cli.py --to-json ~/SatisfactorySavesFolder/SaveGames/76561197970633772/OPO_test.sav opo.json
> Decompression: [######################################################################] ✓ 9099310/9099310
> Traceback (most recent call last):##############################......................]   172218/253794
>   File "/home/alec/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_cli.py", line 340, in <module>
>     (saveFileInfo, headhex, grids, levels, extraObjectReferenceList) = sav_parse.readFullSaveFile(savFilename)
>                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alec/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_parse.py", line 3612, in readFullSaveFile
>     (offset, level) = parseLevel(offset, data, True, progressBar) # Potentially sets the global satisfactoryCalculatorInteractiveMapExtras
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alec/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_parse.py", line 2972, in parseLevel
>     offset = object.parse(offset, data, actorAndComponentObjectHeaders[idx])
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alec/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_parse.py", line 2602, in parse
>     (offset, self.properties, self.propertyTypes) = parseProperties(offset, data)
>                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alec/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_parse.py", line 3390, in parseProperties
>     raise ParseError(f"Unsupported structPropertyType '{structPropertyType}'")
> sav_parse.ParseError: Unsupported structPropertyType 'FGPlayerPortalData'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/alec/Games/SatisfactoryStuff/sav_parse_v1.6_full_release/sav_cli.py", line 360, in <module>
>     raise Exception(f"ERROR: While processing '{savFilename}': {error}")
> Exception: ERROR: While processing '/home/alec/SatisfactorySavesFolder/SaveGames/76561197970633772/OPO_test.sav': **Unsupported structPropertyType 'FGPlayerPortalData'**

I can provide the save file if needed.

**Comment by GreyHak** [comment]
@EricDechane Thank you for bringing this to my attention. If you can attach your game file, I'll fix the parser this evening.

**Comment by EricDechane** [comment]
Save file:
https://drive.google.com/file/d/1Cyo54ynVulY7thiArRIRnER-bvoaiiRx/view?usp=sharing

**Comment by GreyHak** [comment]
@EricDechane  Fix pushed.  Thank you for sharing your save file.

sav_parse.py and sav_to_resave.py have been updated to add FGPlayerPortalData to the generic Properties parser case.
